### ISSUE TITLE
minor issue with latest version using Python3

### ISSUE THREAD

**Issue by gfursin** [SamAinsworth/reproduce-cgo2017-paper#3]
Hi Sam,

Just a note that Python 3 seems not to like tabs.
When I ran updated dashboard on my Windows machine (to view graphs), I got
an error in line 1389 in file 'module/workflow-from-cgo2017-paper/module.py'

    if(not ext.endswith('no-prefetching')):

When I substituted tabs with spaces in front of 'if', it started working fine.
Do you mind to change it, please and commit to main repo?

Thanks a lot!

**Comment by SamAinsworth** [comment]
Ah - apologies! Thanks for finding this - latest commit has got rid of the tabs.

**Comment by gfursin** [comment]
Cool! Thanks, Sam, It works fine now!
