### ISSUE TITLE
Strange problem with plugin on ARM64 

### ISSUE THREAD

**Issue by gfursin** [SamAinsworth/reproduce-cgo2017-paper#4]
Hi Sam,

I installed your artifacts on Tegra X1 development board (ARM64)
and tried to run your experimental workflow. All packages including
CLANG 3.9 and your plugins installed and compiled fine. But
when I try to compile a benchmark using one of your plugins,
I get the following error:

bash ../ck_compile.sh

*** auto ***
clang-3.9   -O3   ../cg.c -Xclang -load -Xclang /home/gfursin/CK-TOOLS/plugin-llvm-sw-prefetch-pass-0.1-llvm-3.9.0-linux-64/lib/SwPrefetchPass.so -c -S -emit-llvm
error: unable to load plugin '/home/gfursin/CK-TOOLS/plugin-llvm-sw-prefetch-pass-0.1-llvm-3.9.0-linux-64/lib/SwPrefetchPass.so':
      '/home/gfursin/CK-TOOLS/plugin-llvm-sw-prefetch-pass-0.1-llvm-3.9.0-linux-64/lib/SwPrefetchPass.so: undefined symbol:
      _ZNK4llvm12FunctionPass17createPrinterPassERNS_11raw_ostreamERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'

I didn't have such problems on X64 and ARMv7, so maybe it's a problem with an official CLANG distribution (I use clang+llvm-3.9.0-aarch64-linux-gnu.tar.xz from http://llvm.org/releases).

Did you ever encounter this problem? If I remember correctly, you use self-compiled CLANG, right? Maybe it's possible to make it compatible with the official CLANG on ARM64? I didn't have time to dig further ... 

Thanks!

**Comment by SamAinsworth** [comment]
Odd! We initially cross-compiled using x86-64 Clang, but for the tests with CK it's natively compiled using the version of Clang automatically installed by CK (3.9).

I get:

bash ../ck_compile.sh

*** auto ***
clang-3.9   -O3   ../cg.c -Xclang -load -Xclang /home/ubuntu/CK-TOOLS/plugin-llvm-sw-prefetch-pass-0.1-llvm-linux-64/lib/SwPrefetchPass.so -c -S -emit-llvm
Can't prefetch load  %54 = load double, double* @amult, align 8, !tbaa !1
Can't prefetch load  %56 = load double, double* @amult, align 8, !tbaa !1
Non-loop-induction phi node!   %49 = phi i32 [ %46, %44 ]
Can't prefetch load  %66 = load i32, i32* %65, align 4, !tbaa !5
....

and so on, where it compiles successfully and detects the relevant loads.

Perhaps there's a different version of the Tegra X1 firmware installed? I recall that the default kernel is 32-bit only, and we were running on an updated one with 64-bit support. We're using R24.1: https://developer.nvidia.com/embedded/linux-tegra-r241

Version information can be viewed by

```
cat /etc/nv_tegra_release
```

Would you please send me the first line output from that? It should start with something along the lines of "# R24 (release), REVISION: 1.0,".

**Comment by gfursin** [comment]
Yes, it's 
# R24 (release), REVISION: 2.1, GCID: 8028265, BOARD: t210ref, EABI: aarch64, DATE: Thu Nov 10 03:51:59 UTC 2016
So, I guess it's the same version ...

**Comment by gfursin** [comment]
Yes, I just thought that it would be simpler for evaluators to use compiler natively, but it may occasionally cause such kind of problems ... Can you try to reproduce this issue on your Tegra machine while using CLANG from CK package, please? Just to be sure that we are on the same page ;) ...

**Comment by SamAinsworth** [comment]
Yes, the text above is from running on the Tegra machine. I'll try and look into any differences, but it does seem to be the same firmware!

**Comment by gfursin** [comment]
Seems like someone had similar error (unfortunately without answers): http://stackoverflow.com/questions/37366291/undefined-symbol-for-self-built-llvm-opt

**Comment by gfursin** [comment]
The fix "-D_GLIBCXX_USE_CXX11_ABI=0" from https://github.com/klee/klee/issues/336 worked! Now I could compile and run apps with your plugin on ARM64 (Tegra X1)! Thanks!
