### ISSUE TITLE
Reproducing results from your paper on ARM64 and X86-64

### ISSUE THREAD

**Issue by gfursin** [SamAinsworth/reproduce-cgo2017-paper#6]
Hi Sam,

I build and ran the latest workflow on my ARM64 (Tegra X1) and x86-64 machines via CK.
The results seem to correspond with ones from your paper.

I attached workflow raw and CK logs, platform description logs (from "ck detect platform"), packed 'result' entry (if someone would like to reuse them further), and PDF from the dashboard to compare results with the pre-recorded ones for both architectures.

Do you mind just to double check them! Thanks a lot!

[ck-aarch64-platform.txt](https://github.com/SamAinsworth/reproduce-cgo2017-paper/files/618731/ck-aarch64-platform.txt)
[ck-aarch64-log-reproduce-results-from-cgo2017-paper.txt](https://github.com/SamAinsworth/reproduce-cgo2017-paper/files/618733/ck-aarch64-log-reproduce-results-from-cgo2017-paper.txt)
[ck-aarch64-workflow.txt](https://github.com/SamAinsworth/reproduce-cgo2017-paper/files/618734/ck-aarch64-workflow.txt)
[ck-aarch64-result-entry.tar.gz](https://github.com/SamAinsworth/reproduce-cgo2017-paper/files/618736/ck-aarch64-result-entry.tar.gz)
[ck-aarch64-dashboard.pdf](https://github.com/SamAinsworth/reproduce-cgo2017-paper/files/618737/ck-aarch64-dashboard.pdf)

[ck-x86-64-platform.txt](https://github.com/SamAinsworth/reproduce-cgo2017-paper/files/618738/ck-x86-64-platform.txt)
[ck-x86-64-log-reproduce-results-from-cgo2017-paper.txt](https://github.com/SamAinsworth/reproduce-cgo2017-paper/files/618739/ck-x86-64-log-reproduce-results-from-cgo2017-paper.txt)
[ck-x86-64-workflow.txt](https://github.com/SamAinsworth/reproduce-cgo2017-paper/files/618740/ck-x86-64-workflow.txt)
[ck-x86-64-result-entry.tar.gz](https://github.com/SamAinsworth/reproduce-cgo2017-paper/files/618742/ck-x86-64-result-entry.tar.gz)
[ck-x86-64-dashboard.pdf](https://github.com/SamAinsworth/reproduce-cgo2017-paper/files/618744/ck-x86-64-dashboard.pdf)

**Comment by SamAinsworth** [comment]
Very good! These all match up very nicely, especially considering the x86-64 systems aren't quite the same processors!

**Comment by gfursin** [comment]
Perfect, thanks!
