### ISSUE TITLE
About Camel microbenchmark

### ISSUE THREAD

**Issue by insoulity** [SamAinsworth/reproduce-cgo2017-paper#8]
Hi Sam,

Thanks for making all your effort including this publicly available! 

I wonder if you can share Camel microbenchmark, described in Code listing 3.2 in your thesis. 

Yongkee

**Comment by SamAinsworth** [comment]
Hi Yongkee,

Both Camel and Kangaroo are described in more detail in our TOCS 2019 paper

https://dl.acm.org/doi/10.1145/3319393

and the benchmarks themselves are in the associated repository:

https://github.com/SamAinsworth/reproduce-tocs2019-paper/tree/master/program/camel
https://github.com/SamAinsworth/reproduce-tocs2019-paper/tree/master/program/kangaroo

The whole repository can be run like the CGO 2017 one, using CK, but as there are many new experiments on Kangaroo in particular, that might take a long time, so you may be better running them yourself by looking up the options in the compile and run scripts in the base folders of the benchmarks themselves. Let me know if you have any issues!

Thanks,
Sam

**Comment by insoulity** [comment]
Hi Sam,

Thanks a lot for the quick response!

I can't believe that I've forgot your TOCS'19 that I went through several times. Now I got to remember not only Camel but also Kangaroo as well. 

Hope you keep safe wherever you stay and best of success in your career,
Yongkee
